source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'bootstrap-sass', '2.3.2.0'
gem 'sass-rails', '~> 4.0.0'
gem 'bourbon'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '~> 1.2'
gem 'will_paginate', '3.0.4'
gem 'bootstrap-will_paginate', '0.0.9'

gem 'mysql2', '~> 0.3.15'

group :production do
  gem 'therubyracer'
end

group :development do
  # better error reports
  gem "binding_of_caller"
  gem "better_errors"

  gem 'rails_best_practices'
end

group :development, :test do
  gem 'byebug'
  gem 'rspec-core', '2.13.0'
  gem 'rspec-rails', '2.13.1'
  gem 'factory_girl_rails', '4.2.1'
end

group :test do
  gem 'faker', '1.3.0'
  gem 'capybara', '2.1.0'
  gem 'launchy'
  gem 'json'
  gem 'cucumber-rails', '1.4.0', :require => false
  gem 'database_cleaner', github: 'bmabey/database_cleaner'

  # PhantomJS driver for Capybara
  gem 'poltergeist', '~> 1.4.1'

  # Uncomment this line on OS X.
  # gem 'growl', '1.0.3'

  # Uncomment these lines on Linux.
  # gem 'libnotify', '0.8.0'

  # Uncomment these lines on Windows.
  # gem 'rb-notifu', '0.0.4'
  # gem 'win32console', '1.3.2'
  # gem 'wdm', '0.1.0'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end